
/vis/open OGL 1366x768-0+0

/vis/viewer/set/autoRefresh false
/vis/verbose errors

/vis/drawVolume
/vis/viewer/zoom 1.3

/vis/scene/add/trajectories smooth

#For example, to select colour by particle ID:
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set mu+ green

#/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
#/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 5

/vis/scene/endOfEventAction accumulate 5000
/vis/scene/endOfRunAction accumulate

/vis/viewer/set/autoRefresh true
/vis/verbose warnings

#/vis/filtering/trajectories/create/originVolumeFilter
#/vis/filtering/trajectories/originVolumeFilter-0/add Detector
#/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add mu+
#/vis/filtering/trajectories/particleFilter-0/add e-
#/vis/filtering/trajectories/particleFilter-0/add gamma

/vis/geometry/set/colour Detector 0 1 0 0 0.6

#/vis/viewer/set/style surface
/vis/viewer/set/hiddenMarker true

/vis/viewer/set/viewpointThetaPhi 0 90
