
/vis/open OGL 1366x768-0+0

/vis/verbose errors

/vis/drawVolume

/vis/viewer/zoom 1.4

/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 1


/vis/geometry/set/colour Abso 0 0 2 0 1.5
/vis/viewer/set/viewpointThetaPhi 130 140

/vis/scene/endOfEventAction accumulate 5000
/vis/scene/endOfRunAction accumulate

/vis/viewer/set/autoRefresh true

/vis/filtering/trajectories/create/particleFilter
/vis/filtering/trajectories/particleFilter-0/add alpha
#/vis/filtering/trajectories/particleFilter-0/invert true


